# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9gNa4DA6scMuJMagcJamzPEkdEac8Dp
"""

a='jish'





"""len(a)"""

a.capitalize()

a.count('i')

a.find('h')

a.startswith('j')

a.isalnum()

a.isnumeric()

a.isalpha()

a.islower()

a.upper()

a.lower()

mark=int(input('enetr u r mark'))
if mark>40:
  print('A+')
elif mark>30 and mark<40:
  print('A')
else:
  print('fail')

name=str(input('enter u r nme'))
age=int(input('enter ur age'))
if age>18:
  if name=='jish':
    print('crct person')
  else:
    print('wrng person')
else:
  print('wrng person')

l=[1,2,3,4,5,6,7,8]
even=0
odd=0
for i in l:
  if i%2==0:
    even=even+1
  else:
    odd=odd+1
print(even)
print(odd)

l=[1,2,3,4,5,6,7,8]
even=0
odd=0
while i%2==0:
    even=even+1
else:
    odd=odd+1
print(even)
print(odd)

for i in range(1,101):
  if not (i%5==0 and i%7==0):
    print(i)

a=10
if (a>5 and a<20):
  print('true')

i=1
while i<11:
  print(i)
  i+=1
  if i==7:
    break

num=int(input('enter a number'))
reverse=int(str(num)[::-1])
if num==reverse:
  print('palindrome')
else:
  print('not palindrom')



num=int(input('enter a number'))
reverse=int(str(num)[::-1])
print(reverse)

num=int(input('enter a number'))
sum=0
temp=num
while temp>0:
  digit = temp%10
  sum += digit**3
  temp //= 10
if num==sum:
  print(num,'is an amstrong no')
else:
  print(num,'not amstrong')

sum=0
for i in range(0,101):
  sum+=i
print(sum,'is the sum')

a=5
b=1
def sum():
  return a+b
sum()

def page(a,b):
  print(a+b)
page(14,35)

def page(a):
  if a>18:
    print("eligible to vote")
  else:
    print("not eligible to vote")
page(15)

double = lambda x,y,z: x+y+z
print(double (5,4,3))

mylist=[1,2,3,4,56,7,8]
newlist=list(filter(lambda x:(x%2==0) ,mylist))
print(newlist)

mylist=[1,2,3,4,5,6,78,]
newlist=list(map(lambda x: x*2,mylist))
print(newlist)

pip install numpy

import numpy as np

a=[1,2,3,4,5]
a

y=np.array([1,2,3,4])
y

y.dtype

y=np.array([1,2,3,4])

y.dtype

y.ndim

np.zeros((3,3),int)

np.full((5,5),8)

np.arange(1,4)

np.random.randint(1,6,2)
np.random.randint(1,6,(3,3))

p=np.array([[1,2,3,4],[6,7,8,9]])
p

np.insert(p,0,5,axis=1)

np.delete(p,2,axis=1)

p=np.array([[1,2,3,4],[6,7,8,9],[23,4,5,5],[33,55,66,77],[1,2,3,4]])
p

